# Generated by Django 4.1.1 on 2023-04-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="name",
            field=models.CharField(default="abs", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
